Assignment5: Assignment5.o
	gcc -o Assignment5 Assignment5.o

Assignment5.o: Assignment5.c Assignment5.h
	gcc -c Assignment5.c
	
t4: t4.o
	gcc -o t4 t4.o

t4.o: t4.c t4.h
	gcc -c t4.c

clean:
	rm -rf *.o Assignment5 t4
